
namespace Language.ErrorHandling;

public enum LdErrorCode
{
    UnknownEscapeSequence = 1000,
    ExpectedIdentifier,
    ExpectedComma,
    ExpectedExpressionReasonMathematical,
    UnexpectedEOF,
    UnrecognizedOperator,
    ArgumentsCanOnlyBeExpressions,
    ExpectedExpressionOrRightParen,
    InvalidFloatLiteral,
    UnknownNumberLiteral,
    ExpectedKeyword,
    ExpectedLeftBrace,
    ExpectedRightBrace,
    ExpectedColonFnArgs,
    ExpectedColon,
    ExpectedClosingGenericCroc,
    ExpectedLeftParen,
    ExpectedRightParen,
    ExpectedArrow,
    UnexpectedToken,
    ExpectedExpression,
    UnknownOperand,
    ExpectedBlockAfterIf,
    ExpectedBlockAfterElse,
    ExpectedLeftBracket,
    ExpectedCommaOrCloseBracket,
    ExpectedRightBracket,
    ExpectedColonStructField,
    ExpectedCommaOrCloseBrace,
    OnlyFunctionsInImplStmts,
    EnumVariantExpectedType,
    ColonNotationOnStructsAndEnums,
    NoModuleFound,
    NoUseMembersSelected,
    NoDeclarationFound,
    TypeDoesNotExist,
    ModuleHadErrors,
    UnsupportedImport,
    ExpectedDoubleColon,
    ExpectedLt,
    ExpectedCommaOrCloseCroc,

    TypeCheckerError = 2500,
    UndefinedType,
    SelfOnUnattachedFunction,
    CouldNotInferType,
    NotAnExpression,
    UndefinedIdentifier,
    CannotCallNonFunctionType,
    UndefinedImplFunction,
    EnumInitializedAsStruct,
    InvalidTypeAssignment,
    InvalidReturn,
    NoExpectedParameters,
    NoImplicitCasts,
    InvalidMathContext
}
